name: PR Testing

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  # In master we want to run for every commit, in other branches — only for the last one
  group: ${{
    ( github.ref == 'refs/heads/master' && format('{0}/{1}/{2}', github.workflow, github.ref, github.sha) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  handle-syncwith:
    name: Call Reusable SyncWith Handler
    uses: NilFoundation/ci-cd/.github/workflows/reusable-handle-syncwith.yml@v1.2.1
    with:
      ci-cd-ref: 'v1.2.1'
    secrets: inherit

  test-linux:
    name: Linux Reusable Crypto3 Testing
    needs:
      - handle-syncwith
    uses: NilFoundation/crypto3/.github/workflows/reusable-submodule-testing-linux.yml@3de0775395bf06c0e4969ff7f921cc7523904269

    secrets: inherit
    with:
      submodules-refs: ${{ needs.handle-syncwith.outputs.prs-refs }}
      check-names: |
        algebra-clang

  # test-mac:
  #   name: Mac Reusable Crypto3 Testing
  #   needs:
  #     - handle-syncwith
  #   uses: NilFoundation/crypto3/.github/workflows/reusable-submodule-testing-mac.yml@3de0775395bf06c0e4969ff7f921cc7523904269

  #   secrets: inherit
  #   with:
  #     submodules-refs: ${{ needs.handle-syncwith.outputs.prs-refs }}
  #     check-names: |
  #       algebra-clang

  publish-results:
    name: Publish JUnit results
    needs:
      - test-linux
    uses: NilFoundation/crypto3/.github/workflows/reusable-publish-result.yml@3de0775395bf06c0e4969ff7f921cc7523904269
