name: PR Testing

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  run-pull-request-actions:
    name: Reusable Crypto3 Testing
    uses: ./.github/workflows/pull-request-action.yml

    secrets: inherit
    with:
      targets: |
        algebra_curves_example
        algebra_curves_test
        algebra_fields_example
        algebra_fields_static_test
        algebra_fields_test
        algebra_hash_to_curve_example
        algebra_hash_to_curve_test
        algebra_multiexp_example
        algebra_multiexp_test
        algebra_pairing_example
        algebra_pairing_test
        algebra_random_element_example
        algebra_short_weierstrass_coordinates_example
        algebra_short_weierstrass_coordinates_test
        algebra_vector_compile_test
        algebra_fields_bench_test
        algebra_curves_bench_test
#        This one fails on GCC: https://github.com/NilFoundation/crypto3-algebra/issues/124
#        algebra_curves_static_test
